Client docker working. Fixed health api

diff --git a/apps/api/Dockerfile b/apps/api/Dockerfile
--- a/apps/api/Dockerfile
+++ b/apps/api/Dockerfile
@@ -1,33 +1,38 @@
-# This file is generated by Nx.
-#
-# Build the docker image with `npx nx docker-build api`.
-# Tip: Modify "docker-build" options in project.json to change docker build args.
-#
-# Run the container with `docker run -p 3000:3000 -t api`.
-FROM node:current-alpine AS BUILD
+FROM node:alpine AS BUILD
 
-WORKDIR /app
+WORKDIR /usr/src/app
 
-COPY ../../dist/apps/api api/
+# Copy package.json and package-lock.json to the working directory
+COPY package*.json ./
 
-# You can remove this install step if you build with `--bundle` option.
-# The bundled output will include external dependencies.
-RUN npm --prefix api --omit=dev -f install
+# Install the application dependencies
+RUN npm install --force
 
-FROM node:current-alpine AS SERVE
+# Copy the rest of the application files
+COPY . .
 
-WORKDIR /app
+# Install the NestJS CLI and build the application, then remove the CLI
+RUN npm run build
+    
+
+FROM node:alpine AS SERVE
+
+WORKDIR /usr/src/app
+
+COPY --from=BUILD /usr/src/app ./
 
 RUN addgroup --system api && \
-          adduser --system -G api api
-
-COPY --from=BUILD /app/api ./api
-#COPY --from=BUILD /app/api/node_modules ./api/node_modules
-
-RUN chown -R api:api .
+    adduser --system -G api api && \
+    chown -R api:api .
 
 ENV HOST=0.0.0.0
 ENV PORT=3000
+#ENV NODE_PATH=/app/node_modules
+EXPOSE 3000
 
 USER api
-CMD [ "node", "api/main.js" ]
+
+# HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
+#   CMD wget --no-verbose --tries=1 --spider http://localhost:3000/api/v1/health/liveness || exit 1
+
+ENTRYPOINT [ "node", "./api/main" ]
